version: '3.8'

services:
  waiting-room-consumer:
    image: openjdk:17-jdk-slim
    container_name: waiting-room-consumer
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    volumes:
      - ./target/${JAR_FILE}:/app/${JAR_FILE}
    restart: always
    working_dir: /app
    command: [ "java", "-jar", "${JAR_FILE}" ]
    networks:
      - ticket-box

networks:
  ticket-box:
    external: true

